export const meta = {
  name: 'triage-itsm',
  description: 'Analyze Hoopit ITSM tickets in parallel: one read-only agent per ticket produces a schema-validated triage verdict. Writing to Jira is done separately by scripts/apply_verdicts.py.',
  phases: [
    { title: 'Analyze', detail: 'one read-only Explore agent per ticket -> schema-validated verdict' },
  ],
}

// args: { keys: string[], skillDir?: string }
// Be robust to args arriving as a JSON string instead of an object.
let A = typeof args === 'string' ? (() => { try { return JSON.parse(args) } catch { return {} } })() : (args || {})
const KEYS = A.keys || []
const SKILL = A.skillDir
if (!SKILL) throw new Error('args.skillDir is required — the orchestrator must pass this skill\'s directory.')
// Base worktrees (pinned to each repo's default branch) prepared by the orchestrator via
// scripts/prepare_base_worktrees.sh and passed in args.repoPaths. No machine-specific fallback.
const REPO_PATHS = Object.assign({}, A.repoPaths || {})

if (!KEYS.length) {
  log('No ticket keys passed in args.keys — nothing to analyze.')
  return []
}
log(`Analyzing ${KEYS.length} ITSM ticket(s). Writes happen separately via scripts/apply_verdicts.py.`)

const VERDICT_SCHEMA = {
  type: 'object',
  additionalProperties: false,
  required: ['key', 'agentSuitability', 'value', 'effort', 'confidence', 'area', 'reproResult', 'needsInfo', 'rootCauseHypothesis', 'comment'],
  properties: {
    key: { type: 'string' },
    agentSuitability: { enum: ['Agent-ready', 'Agent-assisted', 'Human-only', 'Needs-info', 'Not actionable'] },
    value: { enum: ['High', 'Medium', 'Low'] },
    effort: { enum: ['High', 'Medium', 'Low'] },
    confidence: { enum: ['High', 'Medium', 'Low'] },
    area: { enum: ['API', 'Web Admin', 'Flutter App', 'Multiple', 'Unknown'] },
    components: {
      type: 'array',
      description: 'Actual Jira components the fix touches (a combination is fine). Required for Agent-ready.',
      items: { enum: ['Backend', 'Web Admin', 'Flutter', 'Public Website', 'Design'] },
    },
    priorityScore: { type: ['number', 'null'] },
    reproResult: { enum: ['confirmed', 'failed', 'insufficient-info', 'not-applicable'] },
    needsInfo: { type: 'boolean' },
    rootCauseHypothesis: { type: 'string' },
    comment: { type: 'string', description: 'Full plain-text triage comment, MUST begin with the AI disclaimer line. No file paths or line numbers.' },
  },
}

const analyzePrompt = (key) => `You are triaging a single Hoopit ITSM Jira ticket: **${key}**.

You are READ-ONLY. Do not write to Jira and do not edit any files. Produce a calibrated triage verdict.

1. Read the triage rubric and procedure: ${SKILL}/RUBRIC.md (follow it exactly; comment templates are there).
2. Read the ticket: \`acli jira workitem view ${key} --fields '*all' --json\`. If it has attachments (most do — usually HAR files + screenshots), **download and analyze them yourself per ${SKILL}/ATTACHMENTS.md** — acli cannot download attachments, so use the REST API; parse HARs for failing requests (do not read them whole), and view screenshots with the Read tool. Never ask the reporter to review an attachment that is already on the ticket.
3. Read any linked BAC/WEB/FA issue, and parse prior "generated by AI during triage" comments so you don't re-ask resolved questions.
4. Infer the area and explore that repo READ-ONLY to locate the root cause. Use these **base worktrees** (each pinned to the repo's latest default branch — analyze against this production-equivalent state, not any feature branch): API=${REPO_PATHS.api}, Web Admin=${REPO_PATHS['web-admin']}, Flutter App=${REPO_PATHS['flutter-app']}.
5. Classify + score per the rubric, set "components" to the actual Jira component(s) the fix touches (subset of: Backend, Web Admin, Flutter, Public Website, Design — a combination is fine), and write the full triage comment as PLAIN TEXT (acli does not render markdown). It MUST start with the line \`> *This was generated by AI during triage.*\`. For Agent-ready/Agent-assisted/Human-only include an agent brief; for Needs-info use the needs-info template with specific questions to the reporter. **Never put file paths or line numbers in the comment — name classes/methods/types and behavior instead.**

The verdict drives a workflow status downstream: Agent-ready / Agent-assisted / Human-only -> "Pending development" (components are applied); Needs-info -> "Additional information required"; Not actionable -> "Escalated". Reserve "Not actionable" for invalid/duplicate/already-fixed/declined tickets OR ones needing a human product/design decision before any development can be scoped (not merely more info).

Needs-info dominates: if you genuinely cannot assess the ticket without more information from the reporter (missing repro steps/facts), set agentSuitability = "Needs-info" AND needsInfo = true — do NOT also pick Human-only/Agent-ready/Agent-assisted in that case. Conversely, if you have enough to assess and are only flagging a human checkpoint, that is Agent-assisted/Human-only with needsInfo = false.

Return the verdict object. Always populate "components" for actionable tickets (Agent-ready/Agent-assisted/Human-only). needsInfo must be true if and only if agentSuitability is "Needs-info". Leave priorityScore null (it is recomputed deterministically downstream).`

// Deterministic value/effort priority score (don't trust the model to do arithmetic).
const RANK = { High: 3, Medium: 2, Low: 1 }
const withScore = (v) => {
  if (!v) return v
  const scored = v.agentSuitability === 'Agent-ready' || v.agentSuitability === 'Agent-assisted'
  v.priorityScore = scored && RANK[v.value] && RANK[v.effort] ? Math.round((100 * RANK[v.value]) / RANK[v.effort]) : null
  return v
}

const verdicts = (await parallel(
  KEYS.map((key) => () =>
    agent(analyzePrompt(key), { label: `analyze:${key}`, phase: 'Analyze', schema: VERDICT_SCHEMA, agentType: 'Explore', model: 'sonnet' }),
  ),
)).filter(Boolean).map(withScore)

log(`Done: ${verdicts.length}/${KEYS.length} verdict(s). Next: write them to a file and run scripts/apply_verdicts.py (omit --dry-run to write).`)
return verdicts
